### ISSUE TITLE
How can I use the latest citeproc?

### ISSUE THREAD

**Issue by denismaier** [cormacrelf/jest-csl#4]
Citeproc used by this version is not current. How can I update to use the most recent version?

**Comment by cormacrelf** [comment]
I made it so you can exactly specify a version or version range yourself. (You won't be able to use git HEAD, because citeproc-js' repo requires building it.)

https://github.com/cormacrelf/jest-csl/releases/tag/v0.3.1

`npm i citeproc` or `yarn add citeproc` should do the trick once you've updated `jest-csl` to 0.3.1. Thereafter you can use your `package.json` to specify a version.

**Comment by denismaier** [comment]
Cool. Thanks.

**Comment by denismaier** [comment]
Just to be clear: I'll add the information in the top-level `package.json`, right? And after that I'll just call `yarn add citeproc`?
